(function(){
  const view=document.getElementById('app-view');
  let recorder=null,audio=null,timer=null,timerStartedAt=0,timerElapsed=0,pendingApproval=null;
  const currentRoute=()=>PocoRouter.parseRoute(location.hash);
  const go=path=>{location.hash='#/'+path};
  const timerText=seconds=>`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;
  const demoMode=()=>window.LESSON_AGENT_MODE!=='nvidia';
  const notify=message=>{document.querySelector('.app-toast')?.remove();document.body.insertAdjacentHTML('beforeend',`<div class="app-toast" role="status">${message}</div>`);setTimeout(()=>document.querySelector('.app-toast')?.remove(),2200)};
  function stopTimer(){if(timer)clearInterval(timer);timer=null}
  function updateTimer(){const seconds=timerElapsed+(timerStartedAt?Math.floor((Date.now()-timerStartedAt)/1000):0);PocoState.lessonAgent.recordingSeconds=seconds;const target=document.getElementById('agent-timer');if(target)target.textContent=timerText(seconds)}
  function startTimer(){stopTimer();timerElapsed=Number(PocoState.lessonAgent.recordingSeconds)||timerElapsed;timerStartedAt=Date.now();updateTimer();timer=setInterval(updateTimer,250)}
  function pauseTimer(){if(!timerStartedAt)return;timerElapsed+=Math.floor((Date.now()-timerStartedAt)/1000);timerStartedAt=0;stopTimer();updateTimer()}
  function recordContext(){const route=currentRoute(),student=PocoState.students.find(item=>item.id===route.studentId)||PocoState.students[0],record=PocoState.getStudentLessonRecord(student.id,route.recordId);return {studentId:student.id,studentUuid:student.id,recordId:record?.id||route.recordId,session:record?.session||'',studentName:student.nickname||student.name,lessonDate:record?.date||'2026-09-28'}}
  const append=(left,right)=>[left,right].flatMap(value=>Array.isArray(value)?value.map(item=>typeof item==='string'?item:item?.task||''):String(value||'').split('\n')).map(value=>String(value).trim()).filter(Boolean).join('\n');
  function bindRecord(){
    const form=document.querySelector('[data-lesson-record-form]');if(!form)return;
    const {studentId,recordId}=form.dataset,save=form.querySelector('[data-record-save]');
    const sync=()=>{if(save)save.disabled=!PocoState.lessonRecordIsDirty(studentId,recordId)};
    form.querySelectorAll('textarea[name]').forEach(field=>field.addEventListener('input',()=>{const draft=PocoState.lessonRecordDraftFor(studentId,recordId);if(draft)draft[field.name]=field.value;sync()}));
    save?.addEventListener('click',()=>{PocoState.saveStudentLessonRecord(studentId,recordId,false);notify('레슨 기록을 저장했어요.');render()});
    form.querySelector('[data-record-review]')?.addEventListener('click',()=>{PocoState.saveStudentLessonRecord(studentId,recordId,true);notify('레슨 기록을 검토 완료했어요.');render()});
    sync();
  }
  function bindAgent(){
    document.querySelector('[data-lesson-summary-ai]')?.addEventListener('click',()=>{const route=currentRoute();PocoState.resetLessonAgent(recordContext());go(`students/${route.studentId}/lessons/agent/${route.recordId||'8'}`)});
    document.getElementById('agent-start')?.addEventListener('click',async()=>{try{recorder=demoMode()?LessonAgent.createDemoRecorder():LessonAgent.createBrowserRecorder();await recorder.start();timerElapsed=0;Object.assign(PocoState.lessonAgent,LessonAgent.startSession({...PocoState.lessonAgent,previousLessons:PocoState.getStudentLessonRecords(PocoState.lessonAgent.studentId).map(item=>({summary:item.progress||''}))}));render();startTimer()}catch(error){Object.assign(PocoState.lessonAgent,{status:'error',error:error.message});render()}});
    document.getElementById('agent-pause')?.addEventListener('click',()=>{recorder?.pause?.();pauseTimer();Object.assign(PocoState.lessonAgent,{status:'paused'});render()});
    document.getElementById('agent-resume')?.addEventListener('click',()=>{recorder?.resume?.();Object.assign(PocoState.lessonAgent,{status:'recording'});render();startTimer()});
    const finish=async()=>{try{pauseTimer();const blob=await recorder.stop();recorder=null;audio=blob;Object.assign(PocoState.lessonAgent,LessonAgent.stopSession(PocoState.lessonAgent,{durationSeconds:Math.max(1,PocoState.lessonAgent.recordingSeconds),stopConfirmOpen:false}));render();await new Promise(resolve=>setTimeout(resolve,3000));const transcriber=demoMode()?LessonAgent.DemoTranscriptionAdapter:LessonAgent.RemoteTranscriptionAdapter;const analyzer=demoMode()?LessonAgent.DemoAnalysisAdapter:LessonAgent.RemoteAnalysisAdapter;const transcript=await transcriber.transcribe(blob);Object.assign(PocoState.lessonAgent,{transcriptHint:transcript});Object.assign(PocoState.lessonAgent,await LessonAgent.analyzeSession(PocoState.lessonAgent,analyzer));render()}catch(error){Object.assign(PocoState.lessonAgent,{status:'error',error:error.message,stopConfirmOpen:false});render()}};
    document.getElementById('agent-stop')?.addEventListener('click',()=>{recorder?.pause?.();pauseTimer();Object.assign(PocoState.lessonAgent,{status:'paused',stopConfirmOpen:true});render()});
    document.getElementById('agent-stop-cancel')?.addEventListener('click',()=>{PocoState.lessonAgent.stopConfirmOpen=false;render()});
    document.getElementById('agent-stop-confirm')?.addEventListener('click',finish);
    document.getElementById('agent-retry')?.addEventListener('click',()=>{audio=null;PocoState.resetLessonAgent(recordContext());render()});
    document.getElementById('agent-reanalyze')?.addEventListener('click',async event=>{event.preventDefault();event.stopPropagation();const source=audio||(demoMode()?new Blob([new Uint8Array([80,79,67,79])],{type:'audio/opus'}):null);if(!source){notify('다시 분석할 음성 녹음이 없어요.');return}try{Object.assign(PocoState.lessonAgent,{status:'reanalyzing',saveError:''});render();const enhancer=demoMode()?LessonAgent.DemoAudioEnhancementAdapter:LessonAgent.RemoteAudioEnhancementAdapter;const transcriber=demoMode()?LessonAgent.DemoTranscriptionAdapter:LessonAgent.RemoteTranscriptionAdapter;const analyzer=demoMode()?LessonAgent.DemoAnalysisAdapter:LessonAgent.RemoteAnalysisAdapter;const enhanced=await enhancer.enhance(source),transcript=await transcriber.transcribe(enhanced,{enhance:true});Object.assign(PocoState.lessonAgent,{transcriptHint:transcript,status:'analyzing'});Object.assign(PocoState.lessonAgent,await LessonAgent.analyzeSession(PocoState.lessonAgent,analyzer));render()}catch(error){Object.assign(PocoState.lessonAgent,{status:'draft',saveError:error.message});render()}});
    document.getElementById('agent-journal-form')?.addEventListener('submit',event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget).entries()),lines=name=>(values[name]||'').split('\n').map(item=>item.trim()).filter(Boolean);pendingApproval=LessonAgent.approveDraft(PocoState.lessonAgent.draft,{summary:values.summary,repertoire:lines('repertoire').map(value=>{const [title,section,notes]=value.split('·').map(item=>item.trim());return {title,section,notes}}),strengths:lines('strengths'),improvements:lines('improvements'),progressSinceLastLesson:lines('progressSinceLastLesson'),practiceTasks:lines('practiceTasks').map(task=>({task,priority:'high',target:'다음 레슨 전'}))});PocoState.lessonAgent.saveConfirmOpen=true;render()});
    document.getElementById('agent-save-cancel')?.addEventListener('click',()=>{PocoState.lessonAgent.saveConfirmOpen=false;pendingApproval=null;render()});
    document.getElementById('agent-save-confirm')?.addEventListener('click',()=>{if(!pendingApproval)return;const context=recordContext(),record=PocoState.getStudentLessonRecord(context.studentId,context.recordId);if(record)PocoState.updateStudentLessonRecord(context.studentId,context.recordId,{progress:append(record.progress,pendingApproval.summary),strength:append(record.strength,pendingApproval.strengths),difficulty:append(record.difficulty,pendingApproval.improvements),plan:append(record.plan,pendingApproval.practiceTasks),approved:true});PocoState.saveLessonAgentRecord(LessonAgent.toLessonRecord(pendingApproval));go(`students/${context.studentId}/lessons/record/${context.recordId}`)});
  }
  function render(){const current=currentRoute();if(current.name==='lesson-agent'){const student=PocoState.students.find(item=>item.id===current.studentId)||PocoState.students[0];if(PocoState.lessonAgent.studentId!==student.id)PocoState.resetLessonAgent(recordContext());view.innerHTML=PocoViews.lessonAgent(PocoState.lessonAgent)}else{view.innerHTML=PocoViews.students(`${current.studentId}/lessons/record/${current.recordId}`)}bindRecord();bindAgent()}
  window.addEventListener('hashchange',render);if(!location.hash)location.hash='#/students/doyoon/lessons/record/8';else render();
})();
