(function(){
  const students=[{id:'doyoon',name:'박도윤',nickname:'도윤이',instrument:'피아노',level:'중급 초반',material:'체르니 100번 · 1~8번',status:'수업 중'}];
  const lessonRecords={doyoon:[
    {id:'8',session:3,date:'2026.09.24',duration:'60분',instrument:'피아노',progress:'체르니 100번 3번 · 왼손 반주 패턴',strength:'왼손 반주 패턴과 리듬을 안정적으로 연습했어요.',difficulty:'빠른 음형에서 손 모양이 무너져요.',plan:'다음 시간에는 빠른 음형을 느린 속도부터 연습해요.',memo:'손목 힘을 빼도록 안내했어요.',approved:false},
    {id:'7',session:2,date:'2026.09.21',duration:'60분',instrument:'피아노',progress:'체르니 100번 2번',strength:'왼손 반주 패턴과 리듬을 안정적으로 연습했어요.',difficulty:'없음',plan:'체르니 100번 3번으로 진도를 나가요.',memo:'',approved:true},
    {id:'6',session:1,date:'2026.09.17',duration:'60분',instrument:'피아노',progress:'체르니 100번 1번',strength:'왼손 반주 패턴과 리듬을 안정적으로 연습했어요.',difficulty:'없음',plan:'다음 회차 진도를 확인해요.',memo:'',approved:true}
  ]};
  const parseDate=value=>{const match=String(value||'').match(/^(\d{4})[.-](\d{1,2})[.-](\d{1,2})$/);return match?{year:Number(match[1]),month:Number(match[2]),day:Number(match[3])}:null};
  const formatLessonDate=value=>{const parsed=parseDate(value);if(!parsed)return String(value||'');const date=new Date(Date.UTC(parsed.year,parsed.month-1,parsed.day)),days=['일요일','월요일','화요일','수요일','목요일','금요일','토요일'];return `${parsed.month}월 ${parsed.day}일 ${days[date.getUTCDay()]}`};
  const text=value=>Array.isArray(value)?value.map(item=>typeof item==='string'?item:item?.task||'').filter(Boolean).join('\n'):String(value??'');
  const editorValues=record=>({summary:text(record.summary||record.progress),repertoire:text(record.repertoire||record.progress),strengths:text(record.strengths||record.strength),improvements:text(record.improvements||record.difficulty),progressSinceLastLesson:text(record.progressSinceLastLesson),practiceTasks:text(record.practiceTasks||record.plan),progress:record.progress??'',strength:record.strength??'',difficulty:record.difficulty??'',plan:record.plan??'',memo:record.memo??''});
  const getRecords=studentId=>lessonRecords[studentId]||[];
  const getRecord=(studentId,recordId)=>getRecords(studentId).find(record=>record.id===String(recordId))||null;
  const updateRecord=(studentId,recordId,updates)=>{const record=getRecord(studentId,recordId);if(record)Object.assign(record,updates);return record};
  const newLessonAgentState=(context={})=>({status:'ready',studentId:context.studentId||'doyoon',studentUuid:context.studentUuid||context.studentId||'doyoon',recordId:context.recordId||'',session:context.session||'',studentName:context.studentName||'도윤이',lessonDate:context.lessonDate||'2026-09-28',previousLessons:[],draft:null,error:'',saveError:'',recordingSeconds:0,audioRetention:'none',transcriptHint:'',stopConfirmOpen:false,saveConfirmOpen:false});
  const state={students,lessonRecords,getStudentLessonRecords:getRecords,getStudentLessonRecord:getRecord,updateStudentLessonRecord:updateRecord,formatLessonDate,lessonRecordDraft:null,lessonRecordDraftKey:null,lessonAgent:newLessonAgentState(),lessonAgentRecords:[],lessonRecordDraftFor(studentId,recordId){const key=`${studentId}/${recordId}`;if(this.lessonRecordDraftKey!==key){const record=getRecord(studentId,recordId);this.lessonRecordDraft=record?editorValues(record):null;this.lessonRecordDraftKey=key}return this.lessonRecordDraft},lessonRecordIsDirty(studentId,recordId){const record=getRecord(studentId,recordId),draft=this.lessonRecordDraftFor(studentId,recordId),expected=record&&editorValues(record);return Boolean(record&&draft&&expected&&Object.keys(expected).some(field=>String(draft[field]??'')!==String(expected[field]??'')))},saveStudentLessonRecord(studentId,recordId,review=false){const draft=this.lessonRecordDraftFor(studentId,recordId),record=getRecord(studentId,recordId),expected=record&&editorValues(record);if(!draft)return null;const saved=updateRecord(studentId,recordId,{...draft,progress:draft.progress!==expected.progress?draft.progress:draft.repertoire||draft.summary,strength:draft.strength!==expected.strength?draft.strength:draft.strengths,difficulty:draft.difficulty!==expected.difficulty?draft.difficulty:draft.improvements,plan:draft.plan!==expected.plan?draft.plan:draft.practiceTasks,memo:draft.memo,approved:review});this.lessonRecordDraft=null;this.lessonRecordDraftKey=null;return saved},resetLessonAgent(context={}){this.lessonAgent=newLessonAgentState(context);return this.lessonAgent},saveLessonAgentRecord(record){if(record)this.lessonAgentRecords.push(record);return record}};
  window.PocoState=state;
})();
