(function(){
  const esc=value=>String(value==null?'':value).replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const list=(items,empty='아직 기록이 없어요.')=>items&&items.length?`<ul>${items.map(item=>`<li>${esc(typeof item==='string'?item:item.task)}</li>`).join('')}</ul>`:`<p class="muted">${empty}</p>`;
  const timerText=seconds=>{const total=Math.max(0,Number(seconds)||0),minutes=Math.floor(total/60),remaining=total%60;return `${String(minutes).padStart(2,'0')}:${String(remaining).padStart(2,'0')}`};
  const draftFields=draft=>`<div class="agent-journal-grid">
    <label><span class="agent-field-title">수업 전체 요약</span><textarea name="summary">${esc(draft.summary)}</textarea></label>
    <label><span class="agent-field-title">곡·구간</span><textarea name="repertoire">${esc(draft.repertoire.map(item=>`${item.title} · ${item.section} · ${item.notes}`).join('\n'))}</textarea></label>
    <label><span class="agent-field-title">잘된 점</span><textarea name="strengths">${esc(draft.strengths.join('\n'))}</textarea></label>
    <label><span class="agent-field-title">개선할 점</span><textarea name="improvements">${esc(draft.improvements.join('\n'))}</textarea></label>
    <label><span class="agent-field-title">지난 레슨보다 좋아진 점</span><textarea name="progressSinceLastLesson">${esc(draft.progressSinceLastLesson.join('\n'))}</textarea></label>
    <label><span class="agent-field-title">다음 연습 과제</span><textarea name="practiceTasks">${esc(draft.practiceTasks.map(item=>item.task).join('\n'))}</textarea></label>
  </div>`;

  function render(session){
    session=session||{status:'ready',studentName:'도윤이',studentId:'doyoon',lessonDate:'2026-09-28'};
    const status=session.status;
    const comparison=session.draft&&session.draft.progressSinceLastLesson || [];
    let body='';
    if(status==='ready') body=`<div class="agent-ready panel"><img class="agent-character agent-character-ready" src="assets/characters/poconote_뽀꼬_1.png" alt=""><h2>레슨 내용을 안전하게 기록해 보세요</h2><p class="muted">${esc(session.studentName)}의 피아노 레슨을 녹음하고, 선생님이 검토할 수 있는 일지 초안을 만들어요.</p><button class="button primary" id="agent-start">녹음 시작</button></div>`;
    if(status==='recording') body=`<div class="agent-recording panel"><span class="recording-dot"></span><strong class="recording-status-live">녹음 중</strong><div id="agent-timer" class="agent-timer">00:00</div><p class="muted agent-recording-instruction">레슨을 잠시 멈추려면 녹음 중지,<br>종료하려면 녹음 종료를 선택하세요.</p><div class="agent-recording-actions"><button class="button outline" id="agent-pause">녹음 중지</button><button class="button primary" id="agent-stop">녹음 종료</button></div></div>`;
    if(status==='paused') body=`<div class="agent-recording panel"><span class="recording-dot paused"></span><strong>녹음 중지됨</strong><div id="agent-timer" class="agent-timer">${timerText(session.recordingSeconds)}</div><p class="muted agent-recording-instruction">녹음을 잠시 멈췄어요.</p><div class="agent-recording-actions"><button class="button outline" id="agent-resume">녹음 다시 시작</button><button class="button primary" id="agent-stop">녹음 종료</button></div></div>`;
    if(status==='analyzing'||status==='reanalyzing') body=`<div class="agent-processing panel"><img class="agent-character agent-character-processing" src="assets/characters/poconote_뽀꼬_3.png" alt=""><div class="agent-note-loader" aria-label="분석 중"><span>♫</span><span>♫</span><span>♫</span></div><h2>${status==='reanalyzing'?'다시 분석하고 있어요':'레슨 일지를 분석 중이에요'}</h2><p class="muted">녹음에서 곡·구간, 강점, 연습 과제를 추출하고<br>지난 레슨과 비교하고 있습니다.</p><div class="security-status"><strong><span class="security-shield" aria-hidden="true">${PocoIcons.shield}</span>안전한 보안 처리 중</strong><span>OpenShell 샌드박스에서 분석 중 · 네트워크 기본 차단</span></div></div>`;
    if(status==='error') body=`<div class="agent-error panel"><h2>분석을 시작할 수 없어요</h2><p class="muted">${esc(session.error)}</p><button class="button primary" id="agent-retry">다시 녹음하기</button></div>`;
    if(status==='draft'||status==='approved') body=`<div class="agent-journal panel"><div class="panel-head"><div><h2>${esc(session.studentName)} 레슨 일지 ${status==='approved'?'':'초안'}</h2></div></div><div class="security-status"><strong>보안 처리 완료</strong><span>OpenShell 샌드박스 · ${status==='draft'?'검토가 끝날 때까지 임시 보관':'원본 음성: 분석 후 삭제'}</span></div><section class="comparison"><h3>지난 레슨 비교</h3>${list(comparison,'첫 레슨이에요. 비교할 이전 기록이 없습니다.')}</section>${status==='draft'?`<form id="agent-journal-form">${session.saveError?`<p class="agent-save-error" role="alert">${esc(session.saveError)}</p><button class="button outline" type="button" id="agent-save-retry">${session.saving?'저장 중...':'다시 저장'}</button>`:''}${draftFields(session.draft)}<div class="form-actions button-row"><button class="button outline" type="button" id="agent-reanalyze">음성 보정 후 다시 분석</button><button class="button primary" type="submit" ${session.saving?'disabled':''}>${session.saving?'저장 중...':'저장하기'}</button></div></form>`:`<div class="approved-summary"><h3>승인된 레슨 기록</h3><p>${esc(session.draft.summary)}</p><p class="muted">이 결과는 학생별 수업 기록과 리포트에 연결할 수 있습니다.</p></div>`}</div>`;
    const stopConfirm=session.stopConfirmOpen?`<div class="modal-backdrop agent-stop-confirm"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="agent-stop-title"><div class="modal-head"><div><h2 id="agent-stop-title">녹음을 완료할까요?</h2><p>완료하면 AI가 레슨 내용을 분석하기 시작해요.</p></div></div><div class="modal-actions"><button type="button" class="button outline" id="agent-stop-cancel">돌아가기</button><button type="button" class="button primary" id="agent-stop-confirm">완료하기</button></div></section></div>`:'';
    const saveConfirm=session.saveConfirmOpen?`<div class="modal-backdrop agent-save-confirm"><section class="modal" role="dialog" aria-modal="true" aria-labelledby="agent-save-title"><div class="modal-head"><div><h2 id="agent-save-title">이 내용을 저장할까요?</h2><p>저장하면 ${esc(session.session||'')}회차 레슨 기록에 반영돼요.</p></div></div><div class="modal-actions"><button type="button" class="button outline" id="agent-save-cancel">돌아가기</button><button type="button" class="button primary" id="agent-save-confirm">저장하기</button></div></section></div>`:'';
    const resultView=status==='draft'||status==='approved',pageTitle=resultView?'레슨 AI 요약 내용':'레슨 AI로 요약하기',pageDescription=resultView?'AI가 요약한 내용에는 오류가 있을 수 있으니 확인이 필요해요.':'피아노 레슨을 기록하고 핵심을 일지로 정리합니다.';
    return `<section class="view lesson-agent-view"><div class="page-heading"><div><h1>${pageTitle}</h1><p class="muted">${pageDescription}</p></div></div>${body}${stopConfirm}${saveConfirm}</section>`;
  }
  window.PocoViews=window.PocoViews||{};window.PocoViews.lessonAgent=render;
})();
